spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761/eureka/
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: user-service
          uri: lb://USER-SERVICE:8081
          predicates:
            - Path=/api/v1/users/**
#        - id: profile-service
#          uri: lb://PROFILE-SERVICE:8082
#          predicates:
#            - Path=/api/v1/posts/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:5173"
            allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
app:
  eureka-server: localhost
